title = "Michael Wrona"
baseurl = "/"
theme = "hugo-classic"



googleAnalytics = ""
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
# footnotereturnlinkcontents = "↩"

copyright = "Copyright © Michael Wrona 2022"


[params]
custom_css  = ["css/custom-style.css"]
favicon     = "/images/favicon.ico"
# metadata description
description = "Michael Wrona's professional site."


[markup.goldmark.renderer]
unsafe = true

# feather.js social icons
[[params.social]]
    name    = "LinkedIn"
    icon    = "linkedin"
    url     = "https://www.linkedin.com/in/michael-wrona/"

[[params.social]]
    name    = "GitHub"
    icon    = "github"
    url     = "https://github.com/michaelwro"

[[params.social]]
    name    = "YouTube"
    icon    = "youtube"
    url     = ""



# [markup.highlight]
# anchorLineNos = false
# codeFences = true
# guessSyntax = false
# hl_Lines = ""
# lineAnchors = ""
# lineNoStart = 1
# lineNos = false
# lineNumbersInTable = true
# noClasses = true
# style = "monokai"
# tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "education"
    url = "/education/"
    weight = 1

[[menu.main]]
    name = "experience"
    url = "/experience/"
    weight = 2

[[menu.main]]
    name = "awards"
    url = "/awards/"
    weight = 3

[[menu.main]]
    name = "skills"
    url = "/skills/"
    weight = 4

[[menu.main]]
    name = "blog"
    url = "https://mwrona.com"
    weight = 5


# [[menu.main]]
# name = "Categories"
# url = "/categories/"
# weight = 1
# [[menu.main]]
# name = "Tags"
# url = "/tags/"
# weight = 2
# [[menu.feed]]
# name = "Subscribe"
# url = "/index.xml"


